In [1]:
import pandas as pd
car = pd.read_csv("cars.csv", sep=';', header=[0,1])
car.dropna(inplace=True)
car

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
4,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
6,Chevrolet Impala,14.0,8,454.0,220.0,4354.0,9.0,70,US
7,Plymouth Fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US
8,Pontiac Catalina,14.0,8,455.0,225.0,4425.0,10.0,70,US
9,AMC Ambassador DPL,15.0,8,390.0,190.0,3850.0,8.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4,140.0,86.0,2790.0,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82.0,2720.0,19.4,82,US